// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Assignment3Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void InsuranceQuoteCalculation01_Age25Experience3Accidents0_VerifyQuote2500() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("25");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");

            //Assert
      Assert.That(value, Is.EqualTo("$2500"));
    }
  }
  [Test]
  public void InsuranceQuoteCalculation02_Age25Experience3Accidents4_VerifyQuoteNoInsurance() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("25");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("4");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");

            //Assert
      Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
    }
  }
  [Test]
  public void InsuranceQuoteCalculation03_Age35Experience10Accidents2_VerifyQuote1350() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("35");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("10");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("2");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");

            //Assert
      Assert.That(value, Is.EqualTo("$1350"));
    }
  }
  [Test]
  public void InsuranceQuoteCalculation04_InvalidPhoneAge27Experience3Accidents0_VerifyPhoneNumber() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("123");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("27");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
    Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
  }
  [Test]
  public void InsuranceQuoteCalculation05_InvalidEmailAge28Experience3Accidents0_VerifyEmail() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-123-1324");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("wrongemail");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("28");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
    Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
  }
  [Test]
  public void InsuranceQuoteCalculation06_InvalidPostalCodeAge35Experience17Accidents1_VerifyPostalCode() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-123-1324");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("35");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("17");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("1");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
    Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
  }
  [Test]
  public void InsuranceQuoteCalculation07_AgeOmittedExperience17Accidents1_VerifyAge() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("17");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("1");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
    Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
  }
  [Test]
  public void InsuranceQuoteCalculation08_Age37Experience8AccidentsOmitted_VerifyAccidents() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("37");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("8");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
    Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
  }
  [Test]
  public void InsuranceQuoteCalculation09_Age45ExperienceOmittedAccidents0_VerifyExperience() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("45");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
    Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
  }
  [Test]
  public void InsuranceQuoteCalculation10_Age12Experience0Accidents0_VerifyAge() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("12");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("0");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
    Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Please enter a value greater than or equal to 16."));
  }
  [Test]
  public void InsuranceQuoteCalculation11_Age16Experience10Accidents0_VerifyQuoteNoInsurance() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("16");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("10");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");

            //Assert
      Assert.That(value, Is.EqualTo("No Insurance for you!! Driver Age / Experience Not Correct"));
    }
  }
  [Test]
  public void InsuranceQuoteCalculation12_Age28Experience0Accidents0_VerifyQuote4000() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("28");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("0");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");

            //Assert
      Assert.That(value, Is.EqualTo("$4000"));
    }
  }
  [Test]
  public void InsuranceQuoteCalculation13_Age29Experience10Accidents0_VerifyQuote1800() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("29");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("10");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");

            //Assert
      Assert.That(value, Is.EqualTo("$1800"));
    }
  }
  [Test]
  public void InsuranceQuoteCalculation14_Age31Experience3Accidents0_VerifyQuote1875() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("31");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");

        //Assert
      Assert.That(value, Is.EqualTo("$1875"));
    }
  }
  [Test]
  public void InsuranceQuoteCalculation15_CityOmittedAge30Experience3Accidents0_VerifyCity() {

        //Arrange
    driver.Navigate().GoToUrl("http://localhost/prog2070a03/getQuote.html");
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Gloria");
    driver.FindElement(By.Id("lastName")).SendKeys("Rivas-Bonilla");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("123 Street");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("E3E 4E4");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("519-456-1234");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("grivas8325@conestogac.on.ca");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("31");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");

        //Act
    driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
    Assert.That(driver.FindElement(By.Id("city-error")).Text, Is.EqualTo("City is required"));
  }
}
